from gui.add_drinks.add_drinks_widgets.sheet_left.title_template import TitleTemplate
from gui.add_drinks.add_drinks_widgets.sheet_left.ingredients_template import IngredientsTemplate
from gui.add_drinks.add_drinks_widgets.sheet_left.description_template import DescriptionTemplate
from gui.add_drinks.add_drinks_widgets.sheet_left.type_template import TypeTemplate
from gui.add_drinks.add_drinks_widgets.sheet_right.image_template import ImageTemplate
from gui.add_drinks.add_drinks_widgets.sheet_right.confirm_drink_button import ConfirmDrinkButton
from gui.add_drinks.add_drinks_widgets.sheet_right.cancel_drink_button import CancelDrinkButton
